name: Build WPF Designer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        Configuration: [ Debug, Release ]
    env:
        Solution: '**/WpfDesign.sln'
        BuildPlatform: 'Any CPU'
        BuildVersion: '8.0.0.${{ github.run_number }}'
    steps:
    - uses: actions/checkout@v2
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        projectFilter: '**/*.csproj'
        version: ${{ env.BuildVersion }}
        assemblyVersion: ${{ env.BuildVersion }}
        fileVersion: ${{ env.BuildVersion }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: dotnet restore ${{ env.Solution }} -c ${{ matrix.configuration }}
    - name: Build
      run: dotnet build ${{ env.Solution }} --no-restore -c ${{ matrix.configuration }}
    - name: Test
      run: dotnet test ${{ env.Solution }} --no-build --verbosity normal -c ${{ matrix.configuration }}
    - name: Pack
      run:  .\nuget\pack.ps1
    - name: Upload NuGet
      if: matrix.configuration == 'release'
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Packages (${{ matrix.configuration }})
        path: '**/*.nupkg'
        if-no-files-found: error      
 